# Generated by Django 5.0 on 2024-08-08 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0002_trainingcourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='trainingcourse',
            options={'verbose_name': 'Курс обучения', 'verbose_name_plural': 'Курсы обучения'},
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='student',
        ),
        migrations.CreateModel(
            name='AccessToCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_platform.student')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_platform.trainingcourse')),
            ],
            options={
                'verbose_name': 'Доступ к курсу',
                'verbose_name_plural': 'Доступы к курсам',
            },
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='students',
            field=models.ManyToManyField(related_name='courses', through='education_platform.AccessToCourse', to='education_platform.student'),
        ),
    ]
