# Generated by Django 5.0 on 2024-08-08 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0003_alter_student_options_alter_trainingcourse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionForTrainingCourseBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('number', models.IntegerField(verbose_name='Порядковый номер вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос к блоку',
                'verbose_name_plural': 'Вопрос к блоку',
            },
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='description',
            field=models.TextField(default='description', verbose_name='Описание курса обучения'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('is_true', models.BooleanField(verbose_name='Это правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='education_platform.questionfortrainingcourseblock')),
            ],
            options={
                'verbose_name': 'Ответ к вопросу',
                'verbose_name_plural': 'Ответы к вопросам',
            },
        ),
        migrations.CreateModel(
            name='TrainingCourseBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Порядковый номер')),
                ('text', models.TextField(verbose_name='Текст блока обучения')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='education_platform.trainingcourse', verbose_name='Курс обучения')),
            ],
            options={
                'verbose_name': 'Блок обучения',
                'verbose_name_plural': 'Блоки обучения',
            },
        ),
        migrations.AddField(
            model_name='questionfortrainingcourseblock',
            name='training_course_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education_platform.trainingcourseblock'),
        ),
    ]
