# Generated by Django 5.0 on 2024-08-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0004_questionfortrainingcourseblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Бесплатный'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
