# Generated by Django 5.0 on 2024-08-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0006_trainingcourseblock_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='completed_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Прошли обучение'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='time_to_study',
            field=models.PositiveIntegerField(default=0, verbose_name='Время для изучения'),
        ),
        migrations.AddField(
            model_name='trainingcourseblock',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/education_platform/', verbose_name='Загрузить видео'),
        ),
        migrations.AlterField(
            model_name='trainingcourseblock',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
