# Generated by Django 5.0 on 2024-08-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0007_trainingcourse_completed_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='image',
            field=models.ImageField(default='dsa', upload_to='media/education_platform/images/', verbose_name='Обложка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingcourseblock',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/education_platform/video/', verbose_name='Загрузить видео'),
        ),
    ]
