# Generated by Django 5.0 on 2024-08-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0008_trainingcourse_image_alter_trainingcourseblock_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', through='education_platform.AccessToCourse', to='education_platform.student'),
        ),
    ]
