# Generated by Django 5.0 on 2024-08-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0009_alter_trainingcourse_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='author',
            field=models.CharField(default='Sergey Kurilko', max_length=255, verbose_name='Автор курса'),
            preserve_default=False,
        ),
    ]
