# Generated by Django 5.0 on 2024-08-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0012_questionforstep_tag_rename_name_trainingcourse_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWillYouLearnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=255, verbose_name='Чему вы научитесь?')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_will_you_learn_items', to='education_platform.trainingcourse')),
            ],
        ),
    ]
