# Generated by Django 5.0 on 2024-08-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0015_alter_questionforstep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
