# Generated by Django 5.0 on 2024-08-21 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0016_trainingcourse_created_trainingcourse_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointfortrainingblock',
            options={'verbose_name': 'Урок модуля обучения', 'verbose_name_plural': 'Уроки модулей обучения'},
        ),
        migrations.AlterModelOptions(
            name='stepforpoint',
            options={'verbose_name': 'Шаг для урока обучения', 'verbose_name_plural': 'Шаги для уроков обучения'},
        ),
        migrations.AlterModelOptions(
            name='trainingcourseblock',
            options={'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterField(
            model_name='pointfortrainingblock',
            name='number',
            field=models.FloatField(verbose_name='Номер урока'),
        ),
        migrations.AlterField(
            model_name='pointfortrainingblock',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='stepforpoint',
            name='point_for_training_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='education_platform.pointfortrainingblock', verbose_name='Урок обучения'),
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_blocks', models.ManyToManyField(blank=True, to='education_platform.trainingcourseblock')),
                ('completed_points', models.ManyToManyField(blank=True, to='education_platform.pointfortrainingblock')),
                ('completed_steps', models.ManyToManyField(blank=True, to='education_platform.stepforpoint')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_platform.student')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_platform.trainingcourse')),
            ],
            options={
                'verbose_name': 'Прогресс курса',
                'verbose_name_plural': 'Прогресс курсов',
            },
        ),
    ]
