# Generated by Django 5.0 on 2024-08-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0017_alter_pointfortrainingblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointfortrainingblock',
            name='completed_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество прошедших урок'),
        ),
        migrations.AddField(
            model_name='pointfortrainingblock',
            name='time_to_study',
            field=models.PositiveIntegerField(default=0, verbose_name='Время для изучения'),
        ),
        migrations.AddField(
            model_name='pointfortrainingblock',
            name='views_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотревших урок'),
        ),
    ]
