# Generated by Django 5.0 on 2024-08-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0018_pointfortrainingblock_completed_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointfortrainingblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/education_platform/images/points_logo/', verbose_name='Обложка'),
        ),
    ]
