# Generated by Django 5.0 on 2024-08-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0019_pointfortrainingblock_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointfortrainingblock',
            options={'ordering': ['number'], 'verbose_name': 'Урок модуля обучения', 'verbose_name_plural': 'Уроки модулей обучения'},
        ),
        migrations.AlterModelOptions(
            name='questionforstep',
            options={'ordering': ['number'], 'verbose_name': 'Вопрос к шагу', 'verbose_name_plural': 'Вопросы к шагу'},
        ),
        migrations.AlterModelOptions(
            name='stepforpoint',
            options={'ordering': ['number'], 'verbose_name': 'Шаг для урока обучения', 'verbose_name_plural': 'Шаги для уроков обучения'},
        ),
        migrations.AlterModelOptions(
            name='trainingcourseblock',
            options={'ordering': ['number'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
    ]
