# Generated by Django 5.0 on 2024-08-26 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0020_alter_pointfortrainingblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='current_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_blocks', to='education_platform.trainingcourseblock'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='current_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_points', to='education_platform.pointfortrainingblock'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_steps', to='education_platform.stepforpoint'),
        ),
    ]
