# Generated by Django 5.0 on 2024-08-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0021_courseprogress_current_block_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionforstep',
            options={'verbose_name': 'Вопрос к шагу', 'verbose_name_plural': 'Вопрос к шагу'},
        ),
        migrations.RemoveField(
            model_name='questionforstep',
            name='number',
        ),
    ]
