# Generated by Django 5.0 on 2024-08-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0022_alter_questionforstep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
    ]
