# Generated by Django 5.0 on 2024-09-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0023_courseprogress_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointfortrainingblock',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер урока'),
        ),
    ]
