# Generated by Django 5.0 on 2024-09-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0026_student_avatar_alter_stepforpoint_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='education_platform/student/avatars/', verbose_name='Обложка'),
        ),
    ]
