# Generated by Django 5.0 on 2024-09-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0031_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentforstep',
            options={'ordering': ['-published']},
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='author_title',
            field=models.TextField(default='Преподаватель', max_length=155, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='signature',
            field=models.ImageField(default='/', upload_to='media/education_platform/images/signatures/', verbose_name='Подпись автора'),
            preserve_default=False,
        ),
    ]
