# Generated by Django 5.0 on 2024-09-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0032_alter_commentforstep_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Стоимость'),
        ),
    ]
