# Generated by Django 5.0 on 2024-10-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0033_alter_trainingcourse_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='last_action',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя активность'),
        ),
    ]
