# Generated by Django 5.0 on 2024-10-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0034_courseprogress_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='slug',
            field=models.SlugField(default='slug', max_length=255),
            preserve_default=False,
        ),
    ]
