# Generated by Django 5.0 on 2024-10-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0035_trainingcourse_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Скидка'),
        ),
    ]
