# Generated by Django 5.0 on 2024-10-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0036_trainingcourse_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название пакета курсов')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('image', models.ImageField(upload_to='media/education_platform/images/', verbose_name='Обложка')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Пакет курсов',
                'verbose_name_plural': 'Пакеты курсов',
            },
        ),
    ]
