# Generated by Django 5.0 on 2024-10-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0039_coursepack_courses_alter_transaction_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepack',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Краткое описание пакета курсов'),
            preserve_default=False,
        ),
    ]
