# Generated by Django 5.0 on 2024-10-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0040_coursepack_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToCoursePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_platform.coursepack')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_platform.student')),
            ],
            options={
                'verbose_name': 'Доступ к пакету курсов',
                'verbose_name_plural': 'Доступы к пакетам курсов',
            },
        ),
    ]
