# Generated by Django 5.0 on 2024-10-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0041_accesstocoursepack'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='edit_limit',
            field=models.PositiveIntegerField(default=3, verbose_name='Количество редактирований'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='education_platform/student/avatars/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Скидка в процентах'),
        ),
    ]
