# Generated by Django 5.0 on 2024-11-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0044_alter_trainingcourse_options_trainingcourse_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoInDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название баннера')),
                ('image', models.ImageField(upload_to='media/education_platform/images/promo_in_dashboard/', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Основной текст')),
                ('link', models.CharField(max_length=350, verbose_name='Ссылка')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Реклама в содержании курса',
                'verbose_name_plural': 'Рекламы в содержании курса',
            },
        ),
    ]
