# Generated by Django 5.0 on 2024-11-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0046_coursepack_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Начальный уровень'), ('2', 'Средний уровень'), ('3', 'Высокий уровень')], default='2', max_length=1, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название курса'),
        ),
    ]
