# Generated by Django 5.0 on 2024-11-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0048_coursepack_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointfortrainingblock',
            name='completed_counter',
        ),
        migrations.RemoveField(
            model_name='pointfortrainingblock',
            name='views_counter',
        ),
        migrations.RemoveField(
            model_name='stepforpoint',
            name='video_url',
        ),
    ]
