# Generated by Django 5.0 on 2024-11-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0049_remove_pointfortrainingblock_completed_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='signature',
            field=models.FileField(upload_to='media/education_platform/images/signatures/', verbose_name='Подпись автора'),
        ),
    ]
