# Generated by Django 5.0 on 2024-07-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_article_options'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentforarticle',
            options={'verbose_name': 'Комментарий к статье', 'verbose_name_plural': 'Комментарий к статьям'},
        ),
        migrations.AlterField(
            model_name='commentforarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article'),
        ),
        migrations.AlterField(
            model_name='commentforarticle',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comments.client'),
        ),
        migrations.AlterField(
            model_name='commentforarticle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.commentforarticle'),
        ),
    ]
