# Generated by Django 5.0 on 2024-07-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_commentforarticle_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentforarticle',
            name='client',
        ),
        migrations.AddField(
            model_name='commentforarticle',
            name='author',
            field=models.CharField(default='икогнито', max_length=55, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentforarticle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='comments.commentforarticle'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
