# Generated by Django 5.0 on 2024-07-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_commentforarticle_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentforarticle',
            options={'ordering': ['-published'], 'verbose_name': 'Комментарий к статье', 'verbose_name_plural': 'Комментарий к статьям'},
        ),
        migrations.AlterField(
            model_name='commentforarticle',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
