# Generated by Django 5.0 on 2023-12-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_description_remove_article_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='blog/images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
