# Generated by Django 5.0 on 2023-12-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-updated'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.CharField(default='preview', max_length=500, verbose_name='Описание статьи'),
            preserve_default=False,
        ),
    ]
