# Generated by Django 5.0 on 2024-01-23 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(upload_to='promo/service/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='name',
            field=models.CharField(default='Акция', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='promo', to='blog.service'),
        ),
    ]
