# Generated by Django 5.0 on 2024-01-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_promo_published_alter_promo_image_alter_promo_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название курса')),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('format', models.CharField(max_length=250)),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Курс обучения',
                'verbose_name_plural': 'Курсы обучения',
            },
        ),
        migrations.AlterField(
            model_name='promo',
            name='service',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='promo', to='blog.service'),
        ),
        migrations.AddField(
            model_name='promo',
            name='training',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='promo', to='blog.training'),
        ),
    ]
