# Generated by Django 5.0 on 2024-01-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_training_alter_promo_service_promo_training'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='training',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='promo', to='education.training'),
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
