# Generated by Django 5.0 on 2024-01-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_promo_training_delete_training'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='service',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='promo', to='service.service'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
