# Generated by Django 5.0 on 2024-02-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=False, verbose_name='обработано'),
        ),
    ]
