# Generated by Django 5.0 on 2024-02-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_contact_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='relevant',
            field=models.BooleanField(default=True, verbose_name='Актуально'),
        ),
    ]
