# Generated by Django 5.0 on 2024-02-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_contact_relevant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
