# Generated by Django 5.0 on 2024-07-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_counter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Счетчик просмотров'),
        ),
    ]
