# Generated by Django 5.0 on 2024-07-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_article_views_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
