# Generated by Django 5.0 on 2024-07-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг статьи'),
        ),
    ]
