# Generated by Django 5.0 on 2024-07-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_article_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Рейтинг статьи'),
        ),
    ]
