# Generated by Django 5.0 on 2024-02-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_preview_alter_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='preview',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_column_1',
            field=models.TextField(default='left_column', verbose_name='Описание категории услуг - левая колонка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_column_2',
            field=models.TextField(default='right_column', verbose_name='Описание категории услуг - правая колонка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость'),
        ),
    ]
