# Generated by Django 5.0 on 2024-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_service_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='column_1_title',
            field=models.CharField(default='title_left_column', max_length=250, verbose_name='Заголовок левой колонки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='column_2_title',
            field=models.CharField(default='title_right_column', max_length=250, verbose_name='Заголовок правой колонки'),
            preserve_default=False,
        ),
    ]
