# Generated by Django 5.0 on 2024-02-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_servicecategory_column_1_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Краткое описание для карточки'),
        ),
    ]
