# Generated by Django 5.0 on 2024-02-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_servicecategory_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='Категория услуги')),
                ('name', models.CharField(max_length=200, verbose_name='Имя заказчика')),
                ('phone', models.CharField(max_length=18, verbose_name='Телефон')),
                ('question', models.TextField(blank=True, verbose_name='Комментарий заказчика')),
                ('comment', models.TextField(verbose_name='Мои комментарии')),
                ('status', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
        ),
    ]
