# Generated by Django 5.0 on 2024-02-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_orderforservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderforservice',
            options={'verbose_name': 'Заказ услуги', 'verbose_name_plural': 'Заказы услуг'},
        ),
    ]
