# Generated by Django 4.1 on 2024-03-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_servicecategory_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='title',
            field=models.CharField(default='title', max_length=200, verbose_name='title для страницы'),
            preserve_default=False,
        ),
    ]
