# Generated by Django 5.0 on 2024-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название курса')),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('format', models.CharField(max_length=250, verbose_name='Формат обучения')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Курс обучения',
                'verbose_name_plural': 'Курсы обучения',
            },
        ),
    ]
