# Generated by Django 5.0 on 2024-01-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='preview',
            field=models.TextField(default='default', verbose_name='Краткое описание курса (для таблицы)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(verbose_name='Подробное описание курса'),
        ),
    ]
