# Generated by Django 5.0 on 2024-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_training_preview_alter_training_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.FloatField(verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='training',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
