# Generated by Django 5.0 on 2024-01-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_training_duration_alter_training_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['date'], 'verbose_name': 'Курс обучения', 'verbose_name_plural': 'Курсы обучения'},
        ),
    ]
