# Generated by Django 5.0 on 2024-02-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_training_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Курс обучения', 'verbose_name_plural': 'Курсы обучения'},
        ),
        migrations.RemoveField(
            model_name='training',
            name='date',
        ),
        migrations.RemoveField(
            model_name='training',
            name='format',
        ),
        migrations.RemoveField(
            model_name='training',
            name='preview',
        ),
        migrations.AddField(
            model_name='training',
            name='column_1_title',
            field=models.CharField(default='Заголовок левой колонки', max_length=250, verbose_name='Заголовок левой колонки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='column_2_title',
            field=models.CharField(default='Заголовок правой колонки', max_length=250, verbose_name='Заголовок правой колонки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='description_column_1',
            field=models.TextField(default='Текст левой колонки', verbose_name='Текст левой колонки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='description_column_2',
            field=models.TextField(default='Текст правой колонки', verbose_name='Текст правой колонки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='document',
            field=models.CharField(default='документ', max_length=50, verbose_name='Документ об окончании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='form_of_education',
            field=models.CharField(default='форма обучения', max_length=30, verbose_name='Форма обучения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.ImageField(default='изображение', upload_to='education/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='separator_text',
            field=models.CharField(default='разделитель перед блоками', max_length=200, verbose_name='Разделительная строка над блоками'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='short_description',
            field=models.TextField(default='Краткое описание для карточки', verbose_name='Краткое описание курса (для карточки)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='start_date',
            field=models.CharField(default='дата начала курса', max_length=30, verbose_name='Начало обучения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.CharField(max_length=30, verbose_name='Длительность курса'),
        ),
        migrations.AlterField(
            model_name='training',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.CreateModel(
            name='TrainingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.TextField(verbose_name='блок')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_set', to='education.training')),
            ],
        ),
    ]
