# Generated by Django 5.0 on 2024-02-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_training_options_remove_training_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingblock',
            name='title',
            field=models.CharField(default='заголовок блока', max_length=200, verbose_name='заголовок блока'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(upload_to='education/images/', verbose_name='Картинка для карточки'),
        ),
    ]
