# Generated by Django 5.0 on 2024-02-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_trainingblock_title_alter_training_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-rate'], 'verbose_name': 'Курс обучения', 'verbose_name_plural': 'Курсы обучения'},
        ),
        migrations.AddField(
            model_name='training',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
