# Generated by Django 5.0 on 2024-02-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_training_options_training_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-rate', '-pk'], 'verbose_name': 'Курс обучения', 'verbose_name_plural': 'Курсы обучения'},
        ),
    ]
