# Generated by Django 5.0 on 2024-03-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_alter_training_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название курса'),
        ),
    ]
