# Generated by Django 5.0 on 2024-07-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_image_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='reviews/images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
