# Generated by Django 5.0 on 2024-07-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='review',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
