# Generated by Django 5.0 on 2024-02-29 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.CharField(max_length=500, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='portfolio/main_photos/<django.db.models.fields.CharField>/', verbose_name='Фото для карточки')),
                ('bottom_photo', models.ImageField(upload_to='portfolio/bottom_photos/<django.db.models.fields.CharField>/')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='portfolio/gallery_photos/None/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_set', to='portfolio.project', verbose_name='Фотография для галереи')),
            ],
        ),
    ]
