# Generated by Django 5.0 on 2024-02-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Пример выполненной работы', 'verbose_name_plural': 'Примеры выполненных работ'},
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='slug', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='bottom_photo',
            field=models.ImageField(upload_to='portfolio/bottom_photos/', verbose_name='Нижнее фото'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portfolio/main_photos/', verbose_name='Фото для карточки'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='photo',
            field=models.ImageField(upload_to='portfolio/gallery_photos/'),
        ),
    ]
