# Generated by Django 5.0 on 2024-02-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_application', models.CharField(max_length=200, verbose_name='Вид заявки')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('question', models.TextField(verbose_name='Комментарии посетителя')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Когда получено')),
                ('status', models.BooleanField(default=False, verbose_name='Обработано')),
                ('relevant', models.BooleanField(default=True, verbose_name='Актуально')),
                ('comment', models.TextField(default='Мои комментарии', verbose_name='Мои комментарии')),
            ],
            options={
                'verbose_name': 'Заявка от клиента',
                'verbose_name_plural': 'Заявки от клиентов',
            },
        ),
    ]
