# Generated by Django 5.0 on 2024-02-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.ImageField(default='email', upload_to='', verbose_name='email'),
            preserve_default=False,
        ),
    ]
