# Generated by Django 5.0 on 2024-02-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exactly_name_application',
            field=models.CharField(default='конкретно на что заявка', max_length=200, verbose_name='Конкретно на что заявка'),
            preserve_default=False,
        ),
    ]
